export const SET_NAVIGATION_PATH = 'SET_NAVIGATION_PATH';
export const SET_EXTERNAL_ACTION = 'SET_EXTERNAL_ACTION';
export const SET_CURRENT_DETAIL_INDEX = 'navigation/currentDetailIndex';
export const PUSH_TO_NAVIGATION_STACK = 'PUSH_TO_NAVIGATION_STACK';
export const POP_FROM_NAVIGATION_STACK = 'POP_FROM_NAVIGATION_STACK';
export const CLEAR_NAVIGATION_STACK = 'CLEAR_NAVIGATION_STACK';