import {
  ContentMultiMapRemoveKey,
  CredentialKey,
  CrossChainDataRefKey,
  CURRENCY_ADDRESS,
  CurrencyStartNotarizationKey,
  DATA_TYPE_DEFINEDKEY,
  DataByteKey,
  DataByteVectorKey,
  DataCurrencyMapKey,
  DataDescriptorKey,
  DataInt16Key,
  DataInt32Key,
  DataInt32VectorKey,
  DataInt64Key,
  DataInt64VectorKey,
  DataRatingsKey,
  DataStringKey,
  DataTransferDestinationKey,
  DataUint16Key,
  DataUint32Key,
  DataUint64Key,
  DataUint160Key,
  DataUint256Key,
  DataURLKey,
  DataVectorKey,
  EncryptionDescriptorKey,
  ID_ADDRESS_VDXF_KEY,
  ID_FULLYQUALIFIEDNAME_VDXF_KEY,
  ID_PARENT_VDXF_KEY,
  ID_SYSTEMID_VDXF_KEY,
  IDENTITY_AUTH_SIG_VDXF_KEY,
  IDENTITY_CREDENTIAL,
  IDENTITY_CREDENTIAL_PLAINLOGIN,
  IDENTITY_NAME_COMMITMENT_TXID,
  IDENTITY_REGISTRATION_TXID,
  IDENTITY_UPDATE_REQUEST_VDXF_KEY,
  IDENTITY_UPDATE_RESPONSE_VDXF_KEY,
  IDENTITY_UPDATE_TXID,
  LOGIN_CONSENT_CHALLENGE_VDXF_KEY,
  LOGIN_CONSENT_CONTEXT_VDXF_KEY,
  LOGIN_CONSENT_DECISION_VDXF_KEY,
  LOGIN_CONSENT_ID_PROVISIONING_WEBHOOK_VDXF_KEY,
  LOGIN_CONSENT_PROVISIONING_CHALLENGE_VDXF_KEY,
  LOGIN_CONSENT_PROVISIONING_DECISION_VDXF_KEY,
  LOGIN_CONSENT_PROVISIONING_ERROR_KEY_COMMIT_FAILED,
  LOGIN_CONSENT_PROVISIONING_ERROR_KEY_CREATION_FAILED,
  LOGIN_CONSENT_PROVISIONING_ERROR_KEY_NAMETAKEN,
  LOGIN_CONSENT_PROVISIONING_ERROR_KEY_TRANSFER_FAILED,
  LOGIN_CONSENT_PROVISIONING_ERROR_KEY_UNKNOWN,
  LOGIN_CONSENT_PROVISIONING_REQUEST_VDXF_KEY,
  LOGIN_CONSENT_PROVISIONING_RESPONSE_VDXF_KEY,
  LOGIN_CONSENT_PROVISIONING_RESULT_STATE_COMPLETE,
  LOGIN_CONSENT_PROVISIONING_RESULT_STATE_FAILED,
  LOGIN_CONSENT_PROVISIONING_RESULT_STATE_PENDINGAPPROVAL,
  LOGIN_CONSENT_PROVISIONING_RESULT_STATE_PENDINGREQUIREDINFO,
  LOGIN_CONSENT_PROVISIONING_RESULT_VDXF_KEY,
  LOGIN_CONSENT_REDIRECT_VDXF_KEY,
  LOGIN_CONSENT_REQUEST_VDXF_KEY,
  LOGIN_CONSENT_RESPONSE_SIG_VDXF_KEY,
  LOGIN_CONSENT_RESPONSE_VDXF_KEY,
  LOGIN_CONSENT_WEBHOOK_VDXF_KEY,
  MMRDescriptorKey,
  MMRLinksKey,
  MultiMapKey,
  ProfileMediaKey,
  SaltedDataKey,
  SignatureDataKey,
  SIGNED_SESSION_OBJECT,
  SIGNED_SESSION_OBJECT_DATA,
  TypeDefinitionKey,
  UTXORefKey,
  VDXFKeyInterface,
  VectorUint256Key,
  VERUSPAY_INVOICE_VDXF_KEY,
  WALLET_VDXF_KEY,
  ZMemoMessageKey,
  ZMemoSignatureKey,
} from 'verus-typescript-primitives';

const entry = (key: VDXFKeyInterface, label: string): [string, {label: string; fqn: string}] => [
  key.vdxfid,
  {label, fqn: key.qualifiedname.name},
];

// Labels are from Verus Mobile, but changed and capitalized as needed.
const vdxfKeyLabelMap = new Map([
  entry(DataByteKey, 'byte'),
  entry(DataInt16Key, 'int16'),
  entry(DataUint16Key, 'uint16'),
  entry(DataInt32Key, 'int32'),
  entry(DataUint32Key, 'uint32'),
  entry(DataInt64Key, 'int64'),
  entry(DataUint64Key, 'uint64'),
  entry(DataUint160Key, 'uint160'),
  entry(DataUint256Key, 'uint256'),
  entry(DataStringKey, 'string'),
  entry(DataVectorKey, 'vector'),
  entry(DataByteVectorKey, 'byte vector'),
  entry(DataInt32VectorKey, 'int32 vector'),
  entry(DataInt64VectorKey, 'int64 vector'),
  entry(DataCurrencyMapKey, 'currency map'),
  entry(DataRatingsKey, 'ratings'),
  entry(DataURLKey, 'url'),
  entry(DataTransferDestinationKey, 'transfer destination'),
  entry(UTXORefKey, 'utxo ref'),
  entry(CrossChainDataRefKey, 'cross chain data ref'),
  entry(EncryptionDescriptorKey, 'encryption descriptor'),
  entry(SaltedDataKey, 'salted data'),
  entry(DataDescriptorKey, 'data descriptor'),
  entry(SignatureDataKey, 'signature data'),
  entry(VectorUint256Key, 'vector uint256'),
  entry(MMRLinksKey, 'mmr links'),
  entry(MMRDescriptorKey, 'mmr descriptor'),
  entry(TypeDefinitionKey, 'type definition'),
  entry(MultiMapKey, 'multi map'),
  entry(ContentMultiMapRemoveKey, 'content multi map remove'),
  entry(ProfileMediaKey, 'profile media'),
  entry(ZMemoMessageKey, 'z memo message'),
  entry(ZMemoSignatureKey, 'z memo signature'),
  entry(CurrencyStartNotarizationKey, 'currency start notarization'),
  entry(VERUSPAY_INVOICE_VDXF_KEY, 'veruspay invoice'),
  entry(IDENTITY_UPDATE_REQUEST_VDXF_KEY, 'identity update request'),
  entry(IDENTITY_UPDATE_RESPONSE_VDXF_KEY, 'identity update response'),
  entry(IDENTITY_AUTH_SIG_VDXF_KEY, 'identity auth signature'),
  entry(LOGIN_CONSENT_RESPONSE_SIG_VDXF_KEY, 'login consent response signature'),
  entry(LOGIN_CONSENT_REQUEST_VDXF_KEY, 'login consent request'),
  entry(LOGIN_CONSENT_RESPONSE_VDXF_KEY, 'login consent response'),
  entry(LOGIN_CONSENT_CHALLENGE_VDXF_KEY, 'login consent challenge'),
  entry(LOGIN_CONSENT_DECISION_VDXF_KEY, 'login consent decision'),
  entry(WALLET_VDXF_KEY, 'wallet'),
  entry(LOGIN_CONSENT_REDIRECT_VDXF_KEY, 'login consent redirect'),
  entry(LOGIN_CONSENT_WEBHOOK_VDXF_KEY, 'login consent webhook'),
  entry(LOGIN_CONSENT_CONTEXT_VDXF_KEY, 'login consent context'),
  entry(LOGIN_CONSENT_ID_PROVISIONING_WEBHOOK_VDXF_KEY, 'login consent id provisioning webhook'),
  entry(ID_ADDRESS_VDXF_KEY, 'id address'),
  entry(ID_SYSTEMID_VDXF_KEY, 'id system id'),
  entry(ID_FULLYQUALIFIEDNAME_VDXF_KEY, 'id fully qualified name'),
  entry(ID_PARENT_VDXF_KEY, 'id parent'),
  entry(LOGIN_CONSENT_PROVISIONING_REQUEST_VDXF_KEY, 'login consent provisioning request'),
  entry(LOGIN_CONSENT_PROVISIONING_CHALLENGE_VDXF_KEY, 'login consent provisioning challenge'),
  entry(LOGIN_CONSENT_PROVISIONING_DECISION_VDXF_KEY, 'login consent provisioning decision'),
  entry(LOGIN_CONSENT_PROVISIONING_RESPONSE_VDXF_KEY, 'login consent provisioning response'),
  entry(LOGIN_CONSENT_PROVISIONING_RESULT_VDXF_KEY, 'login consent provisioning result'),
  entry(IDENTITY_NAME_COMMITMENT_TXID, 'identity name commitment txid'),
  entry(IDENTITY_REGISTRATION_TXID, 'identity registration txid'),
  entry(IDENTITY_UPDATE_TXID, 'identity update txid'),
  entry(
    LOGIN_CONSENT_PROVISIONING_RESULT_STATE_PENDINGREQUIREDINFO,
    'provisioning result state pending required info'
  ),
  entry(
    LOGIN_CONSENT_PROVISIONING_RESULT_STATE_PENDINGAPPROVAL,
    'provisioning result state pending approval'
  ),
  entry(LOGIN_CONSENT_PROVISIONING_RESULT_STATE_COMPLETE, 'provisioning result state complete'),
  entry(LOGIN_CONSENT_PROVISIONING_RESULT_STATE_FAILED, 'provisioning result state failed'),
  entry(LOGIN_CONSENT_PROVISIONING_ERROR_KEY_NAMETAKEN, 'provisioning error name taken'),
  entry(LOGIN_CONSENT_PROVISIONING_ERROR_KEY_UNKNOWN, 'provisioning error unknown'),
  entry(LOGIN_CONSENT_PROVISIONING_ERROR_KEY_COMMIT_FAILED, 'provisioning error commit failed'),
  entry(LOGIN_CONSENT_PROVISIONING_ERROR_KEY_CREATION_FAILED, 'provisioning error creation failed'),
  entry(LOGIN_CONSENT_PROVISIONING_ERROR_KEY_TRANSFER_FAILED, 'provisioning error transfer failed'),
  entry(SIGNED_SESSION_OBJECT_DATA, 'signed session object data'),
  entry(SIGNED_SESSION_OBJECT, 'signed session object'),
  entry(CURRENCY_ADDRESS, 'currency address'),
  entry(DATA_TYPE_DEFINEDKEY, 'vdxf key definitions'),
  entry(IDENTITY_CREDENTIAL, 'Credentials'),
  entry(CredentialKey, 'Credential'),
  entry(IDENTITY_CREDENTIAL_PLAINLOGIN, 'Plain Login'),
]);

export function getVDXFKeyLabel(key: string): string;
export function getVDXFKeyLabel(key: string, nullOnMiss: boolean): string | null;
export function getVDXFKeyLabel(key: string, nullOnMiss = false): string | null {
  const entry = vdxfKeyLabelMap.get(key);
  if (entry != null) {
    return entry.label;
  }
  if (nullOnMiss) {
    return null;
  }
  return key.substring(0, 4) + '...' + key.substring(key.length - 4);
}

export function getKnownVDXFKeyName(key: string): string | null {
  const entry = vdxfKeyLabelMap.get(key);
  if (entry != null) {
    return entry.fqn;
  }
  return null;
}
